export type OsrsWikiQuestRow = { name: string; is_members: boolean };

export const OSRS_WIKI_QUESTS: OsrsWikiQuestRow[] = [
  { name: "A Kingdom Divided", is_members: true },
  { name: "A Night at the Theatre", is_members: true },
  { name: "A Porcine of Interest", is_members: true },
  { name: "A Soul's Bane", is_members: true },
  { name: "A Tail of Two Cats", is_members: true },
  { name: "A Taste of Hope", is_members: true },
  { name: "Animal Magnetism", is_members: true },
  { name: "Another Slice of H.A.M.", is_members: true },
  { name: "At First Light", is_members: true },
  { name: "Below Ice Mountain", is_members: false },
  { name: "Beneath Cursed Sands", is_members: true },
  { name: "Between a Rock...", is_members: true },
  { name: "Big Chompy Bird Hunting", is_members: true },
  { name: "Biohazard", is_members: true },
  { name: "Black Knights' Fortress", is_members: false },
  { name: "Bone Voyage", is_members: true },
  { name: "Cabin Fever", is_members: true },
  { name: "Children of the Sun", is_members: true },
  { name: "Client of Kourend", is_members: true },
  { name: "Clock Tower", is_members: true },
  { name: "Cold War", is_members: true },
  { name: "Contact!", is_members: true },
  { name: "Cook's Assistant", is_members: false },
  { name: "Creature of Fenkenstrain", is_members: true },
  { name: "Current Affairs", is_members: true },
  { name: "Darkness of Hallowvale", is_members: true },
  { name: "Death on the Isle", is_members: true },
  { name: "Death Plateau", is_members: true },
  { name: "Death to the Dorgeshuun", is_members: true },
  { name: "Defender of Varrock", is_members: true },
  { name: "Demon Slayer", is_members: false },
  { name: "Desert Treasure I", is_members: true },
  { name: "Desert Treasure II - The Fallen Empire", is_members: true },
  { name: "Devious Minds", is_members: true },
  { name: "Doric's Quest", is_members: false },
  { name: "Dragon Slayer I", is_members: false },
  { name: "Dragon Slayer II", is_members: true },
  { name: "Dream Mentor", is_members: true },
  { name: "Druidic Ritual", is_members: true },
  { name: "Dwarf Cannon", is_members: true },
  { name: "Eadgar's Ruse", is_members: true },
  { name: "Eagles' Peak", is_members: true },
  { name: "Elemental Workshop I", is_members: true },
  { name: "Elemental Workshop II", is_members: true },
  { name: "Enakhra's Lament", is_members: true },
  { name: "Enlightened Journey", is_members: true },
  { name: "Ernest the Chicken", is_members: false },
  { name: "Ethically Acquired Antiquities", is_members: true },
  { name: "Fairytale I - Growing Pains", is_members: true },
  { name: "Fairytale II - Cure a Queen", is_members: true },
  { name: "Family Crest", is_members: true },
  { name: "Fight Arena", is_members: true },
  { name: "Fishing Contest", is_members: true },
  { name: "Forgettable Tale...", is_members: true },
  { name: "Garden of Tranquillity", is_members: true },
  { name: "Gertrude's Cat", is_members: true },
  { name: "Getting Ahead", is_members: true },
  { name: "Ghosts Ahoy", is_members: true },
  { name: "Goblin Diplomacy", is_members: false },
  { name: "Grim Tales", is_members: true },
  { name: "Haunted Mine", is_members: true },
  { name: "Hazeel Cult", is_members: true },
  { name: "Heroes' Quest", is_members: true },
  { name: "Holy Grail", is_members: true },
  { name: "Horror from the Deep", is_members: true },
  { name: "Icthlarin's Little Helper", is_members: true },
  { name: "Imp Catcher", is_members: false },
  { name: "In Aid of the Myreque", is_members: true },
  { name: "In Search of the Myreque", is_members: true },
  { name: "Jungle Potion", is_members: true },
  { name: "King's Ransom", is_members: true },
  { name: "Land of the Goblins", is_members: true },
  { name: "Learning the Ropes", is_members: false },
  { name: "Legends' Quest", is_members: true },
  { name: "Lost City", is_members: true },
  { name: "Lunar Diplomacy", is_members: true },
  { name: "Making Friends with My Arm", is_members: true },
  { name: "Making History", is_members: true },
  { name: "Meat and Greet", is_members: true },
  { name: "Merlin's Crystal", is_members: true },
  { name: "Misthalin Mystery", is_members: false },
  { name: "Monk's Friend", is_members: true },
  { name: "Monkey Madness I", is_members: true },
  { name: "Monkey Madness II", is_members: true },
  { name: "Mountain Daughter", is_members: true },
  { name: "Mourning's End Part I", is_members: true },
  { name: "Mourning's End Part II", is_members: true },
  { name: "Murder Mystery", is_members: true },
  { name: "My Arm's Big Adventure", is_members: true },
  { name: "Nature Spirit", is_members: true },
  { name: "Observatory Quest", is_members: true },
  { name: "Olaf's Quest", is_members: true },
  { name: "One Small Favour", is_members: true },
  { name: "Pandemonium", is_members: true },
  { name: "Perilous Moons", is_members: true },
  { name: "Pirate's Treasure", is_members: false },
  { name: "Plague City", is_members: true },
  { name: "Priest in Peril", is_members: true },
  { name: "Prince Ali Rescue", is_members: false },
  { name: "Prying Times", is_members: true },
  { name: "Rag and Bone Man I", is_members: true },
  { name: "Rag and Bone Man II", is_members: true },
  { name: "Ratcatchers", is_members: true },
  { name: "Recipe for Disaster", is_members: true },
  { name: "Recruitment Drive", is_members: true },
  { name: "Regicide", is_members: true },
  { name: "Romeo & Juliet", is_members: false },
  { name: "Roving Elves", is_members: true },
  { name: "Royal Trouble", is_members: true },
  { name: "Rum Deal", is_members: true },
  { name: "Rune Mysteries", is_members: false },
  { name: "Scorpion Catcher", is_members: true },
  { name: "Scrambled!", is_members: true },
  { name: "Sea Slug", is_members: true },
  { name: "Secrets of the North", is_members: true },
  { name: "Shades of Mort'ton", is_members: true },
  { name: "Shadow of the Storm", is_members: true },
  { name: "Shadows of Custodia", is_members: true },
  { name: "Sheep Herder", is_members: true },
  { name: "Sheep Shearer", is_members: false },
  { name: "Shield of Arrav", is_members: false },
  { name: "Shilo Village", is_members: true },
  { name: "Sins of the Father", is_members: true },
  { name: "Sleeping Giants", is_members: true },
  { name: "Song of the Elves", is_members: true },
  { name: "Spirits of the Elid", is_members: true },
  { name: "Swan Song", is_members: true },
  { name: "Tai Bwo Wannai Trio", is_members: true },
  { name: "Tale of the Righteous", is_members: true },
  { name: "Tears of Guthix", is_members: true },
  { name: "Temple of Ikov", is_members: true },
  { name: "Temple of the Eye", is_members: true },
  { name: "The Ascent of Arceuus", is_members: true },
  { name: "The Blood Moon Rises", is_members: true },
  { name: "The Corsair Curse", is_members: false },
  { name: "The Curse of Arrav", is_members: true },
  { name: "The Depths of Despair", is_members: true },
  { name: "The Dig Site", is_members: true },
  { name: "The Eyes of Glouphrie", is_members: true },
  { name: "The Feud", is_members: true },
  { name: "The Final Dawn", is_members: true },
  { name: "The Forsaken Tower", is_members: true },
  { name: "The Fremennik Exiles", is_members: true },
  { name: "The Fremennik Isles", is_members: true },
  { name: "The Fremennik Trials", is_members: true },
  { name: "The Garden of Death", is_members: true },
  { name: "The Giant Dwarf", is_members: true },
  { name: "The Golem", is_members: true },
  { name: "The Grand Tree", is_members: true },
  { name: "The Great Brain Robbery", is_members: true },
  { name: "The Hand in the Sand", is_members: true },
  { name: "The Heart of Darkness", is_members: true },
  { name: "The Ides of Milk", is_members: false },
  { name: "The Knight's Sword", is_members: false },
  { name: "The Lost Tribe", is_members: true },
  { name: "The Path of Glouphrie", is_members: true },
  { name: "The Queen of Thieves", is_members: true },
  { name: "The Red Reef", is_members: true },
  { name: "The Restless Ghost", is_members: false },
  { name: "The Ribbiting Tale of a Lily Pad Labour Dispute", is_members: true },
  { name: "The Slug Menace", is_members: true },
  { name: "The Tourist Trap", is_members: true },
  { name: "Throne of Miscellania", is_members: true },
  { name: "Tower of Life", is_members: true },
  { name: "Tree Gnome Village", is_members: true },
  { name: "Tribal Totem", is_members: true },
  { name: "Troll Romance", is_members: true },
  { name: "Troll Stronghold", is_members: true },
  { name: "Troubled Tortugans", is_members: true },
  { name: "Twilight's Promise", is_members: true },
  { name: "Underground Pass", is_members: true },
  { name: "Vampyre Slayer", is_members: false },
  { name: "Wanted!", is_members: true },
  { name: "Watchtower", is_members: true },
  { name: "Waterfall Quest", is_members: true },
  { name: "What Lies Below", is_members: true },
  { name: "While Guthix Sleeps", is_members: true },
  { name: "Witch's House", is_members: true },
  { name: "Witch's Potion", is_members: false },
  { name: "X Marks the Spot", is_members: false },
  { name: "Zogre Flesh Eaters", is_members: true },
];
